#!/bin/bash

go build -i -v  -ldflags '-w -s' -o ${GOPATH}/bin/r53-ufw-client r53-ufw/client

go build -i -v  -ldflags '-w -s' -o ${GOPATH}/bin/r53-ufw-server r53-ufw/server

go build -i -v  -ldflags '-w -s' -o ${GOPATH}/bin/r53-ufw-admin r53-ufw/admin
