#!/bin/bash

go build -i -v  -ldflags '-w -s' -o ${GOPATH}/bin/r53-ufw-client github.com/my10c/r53-ufw/client

go build -i -v  -ldflags '-w -s' -o ${GOPATH}/bin/r53-ufw-server github.com/my10c/r53-ufw/server

go build -i -v  -ldflags '-w -s' -o ${GOPATH}/bin/r53-ufw-admin github.com/my10c/r53-ufw/admin
